baseURL = "hhttps://coursinfo.ca/420-5D4/linux/"
languageCode = "fr-ca"
DefaultContentLanguage = "fr"
theme = "hugo-theme-learn"
[params]
themeVariant = "green"
titleSeparator = ""
landingPageURL = "hhttps://coursinfo.ca/420-5D4/linux/"
landingPageName = "<i class='fas fa-home'></i> Accueil"
disableSearch = true
logo = "images/logo.png"
